The Celsius symbol is not encoded in UTF-8
The Celsius symbol is \xb0, which is not a valid utf8 encoding. Change it to \xc2\xb0

ERROR: xgettext failed to generate PO tempalte file because the following
       file contains strings marked for translation, not encoded in UTF-8.
       Please ensure all strings marked for translation are UTF-8 encoded.

           unknown